### ISSUE TITLE
Is it still in development?

### ISSUE THREAD

**Issue by SalahAdDin** [itisnajim/strapi-plugin-fcm#1]
Looking for new and good plugins for Strapi, I found this plugin, it would be useful for a project we were developing for around one year with a small but not complete configuration.

I would like to test this and use it for further projects, but I saw it is not in **npm** anymore.

Why?

Luis

**Comment by itisnajim** [comment]
The npm page exists: 
https://www.npmjs.com/package/strapi-plugin-fcm

Try to uninstall and reinstall: 
npm i strapi-plugin-fcm@1.0.2

**Comment by SalahAdDin** [comment]
> The npm page exists: https://www.npmjs.com/package/strapi-plugin-fcm
> 
> Try to uninstall and reinstall: npm I strapi-plugin-fcm@1.0.2

why it is not accessible from the marketplace?

**Comment by itisnajim** [comment]
1.0.0
Not exist, uninstall & try 1.0.2

**Comment by SalahAdDin** [comment]
> 1.0.0 or 1.0.1 Not exist, uninstall & try 1.0.2

Cool to hear it, i will use it then.
