### ISSUE TITLE
Get notifications via api

### ISSUE THREAD

**Issue by ApostolosMavroukakis** [itisnajim/strapi-plugin-fcm#16]
im trying to expose the notifications to the api for some testing and i cant seem to be able to find the endpoints via the api based on the provided documentation. Ive opened up the role to be able to find them but i tried to hit /api/fcm-notifications and /api/fcm-notification 

![image](https://github.com/itisnajim/strapi-plugin-fcm/assets/9714171/1da8a0cf-1766-46d8-83f9-b3ec64e1ea7e)

![image](https://github.com/itisnajim/strapi-plugin-fcm/assets/9714171/39ffc68d-ce0f-4b92-a630-37137fef909e)

**Comment by ApostolosMavroukakis** [comment]
Fyi im trying to hit /api/fcm-notifications or /api/fcm-notification and i get 404

**Comment by itisnajim** [comment]
click on the gear icon next find to find the correct api path

**Comment by ApostolosMavroukakis** [comment]
> click on the gear icon next find to find the correct api path

oh jesus christ thank you so much i feel so dumb
