### ISSUE TITLE
Node v18 not supported

### ISSUE THREAD

**Issue by nayi10** [itisnajim/strapi-plugin-fcm#17]
First of all, thank you for this great package. Would you please add support for Node version 18+? The current version is pinned to Node v12+ to v16+.

This is the error I get when I try to use this with v18+:

> error strapi-plugin-fcm@1.0.7: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.15.0"

**Comment by itisnajim** [comment]
you're welcome!
i've published a new version `1.0.8` and it should add the support for Node v18
