### ISSUE TITLE
https://server/api/strapi-plugin-fcm/fcm-targets return  null data

### ISSUE THREAD

**Issue by Cosbiome** [itisnajim/strapi-plugin-fcm#2]
At the time of sending the notification it does not bring me the users configured in the up_users tokenpush and I have tried in different ways to solve it but I understand the documentation completely well or it may be a small bug
![Captura de Pantalla 2022-08-19 a la(s) 17 04 31](https://user-images.githubusercontent.com/62185271/185713152-884d5107-d35e-4cc5-be4d-92c758758307.png)
![Captura de Pantalla 2022-08-19 a la(s) 17 06 05](https://user-images.githubusercontent.com/62185271/185713300-c360f60a-0eb4-44ed-9c0d-952d86550ce4.png)
![Captura de Pantalla 2022-08-19 a la(s) 17 05 22](https://user-images.githubusercontent.com/62185271/185713231-4858f2e5-b86f-4b56-9d0e-8627e381a8d5.png)

**Comment by itisnajim** [comment]
sry for the late response, i'm in a vacation, 
make sure that the `user` is not a draft (`published_at` not null) and `tokenpush` not empty

**Comment by Cosbiome** [comment]
> sry for the late response, i'm in a vacation, make sure that the `user` is not a draft (`published_at` not null) and `tokenpush` not empty
![Captura de Pantalla 2022-08-26 a la(s) 16 03 23](https://user-images.githubusercontent.com/62185271/186990298-5bd245c9-dd02-42e5-b720-69a939b85b56.png)
![Captura de Pantalla 2022-08-26 a la(s) 16 03 41](https://user-images.githubusercontent.com/62185271/186990332-bcff344f-422e-416f-a64e-aa202b9fceb2.png)

Without any problem I hope you are enjoying your vacations, I already verified tokenpush is not null and up_user does not have a published_at system it keeps throwing me the same errors

**Comment by itisnajim** [comment]
i'm using postgres as a database, which database you selected ?

**Comment by Cosbiome** [comment]
MariaDB

**Comment by l4red0** [comment]
@Cosbiome I have encountered the same problem, also using mysql. Apparently mysql/mariadb returns results in a different structure than postgres. I don't know what the original object from postgrest looks like but most likely mysql adds a second array.

I've changed all `result.rows` (:78,84) to `results[0]` in `./serer/services/fc-target.js`. This done the trick for me although it's obviously a quick fix.

**Comment by itisnajim** [comment]
hello guys, 
@Cosbiome you can now update `strapi-plugin-fcm` to `1.0.4` and check, thanks to @l4red0 i did the fix he proposed  without testing, i trust him xD
i suggest to upgrade `Strapi` to `>= 4.2.2` if not working!

**Comment by jimodelid** [comment]
My result seem to come up empty, no users to show, no topics to show even though I've got users and topics. I use the default installation so I presume it's sqlite? Running version 4.4.5 (latest). Are you able to assist?

> hello guys,
> @Cosbiome you can now update `strapi-plugin-fcm` to `1.0.4` and check, thanks to @l4red0 i did the fix he proposed without testing, i trust him xD
> i suggest to upgrade `Strapi` to `>= 4.2.2` if not working! or/and re-comment here and i'll go more deep into the fixing issue.

**Comment by itisnajim** [comment]
fixed
https://github.com/itisnajim/strapi-plugin-fcm/pull/5
