### ISSUE TITLE
Error: ./src/plugins/strapi-plugin-fcm couldn't be resolved

### ISSUE THREAD

**Issue by themtaysw** [itisnajim/strapi-plugin-fcm#8]
just installed it and this error popped up once I ran yarn build

```
Error: ./src/plugins/strapi-plugin-fcm couldn't be resolved
    at toDetailedDeclaration (/Users/matejmatiasko/Desktop/matysw.com/api/node_modules/@strapi/strapi/lib/core/loaders/plugins/get-enabled-plugins.js:39:15)
```

**Comment by itisnajim** [comment]
Please try using npm instead of yarn and let me know if it works. I am available to assist you.

**Comment by chandrashekhar07** [comment]
On a fresh install from yarn, i was also getting the same issues. Like @itisnajim suggested, I have shifted to npm and again I have reverted to yarn. Now it is working perfectly with yarn
